
NUM_WORKERS: 8
BATCH_SIZE: 4

CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints/best
  PIPELINE_PATH: configs/se_resnext50_32
  PIPELINE_NAME: se_resnext50_32

DICT_FOLDER: 'dict_se_resnext50_32'
SUBMIT_BEST: True
USEFOLDS: [0,1,2,3,4,5,6,7]
SELECTED_CHECKPOINTS:
  fold7: [57,59]
RESULT: result_top3.pkl
