PIPELINE_NAME: efficientnet-b3
PREPARE_FOLDS: TRUE
LOGGER_DIR: 'log'

IDS_FILES:
    TRAIN_FILE: folds/
    TEST_FILE: folds/test_id.csv

CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints/best
  TOPK: 4

EPOCHES: 35

DATA_PARAMS:
  data_folder: 'cloudsimg/train_images'
  num_workers: 10
  batch_size: 2

train_params:
  metrics:
      utils.loss.DiceBCELoss:
          weight: None
          size_average: TRUE

FOLD:
  NUMBER: 3
  USEFOLDS: [0,1,2]

OPTIMIZER:
  CLASS: Adam
  ARGS:
    lr: 0.000075
    weight_decay: 0.00001
    
SCHEDULER:
 CLASS: CosineAnnealingLR
 ARGS: 
   T_max: 8
   eta_min: 0.0000001       

ENCODER: resnet34