PIPELINE_NAME: efficientnet-b3
TRAIN_PATH: 'cloudsimg/train_images'
PREPARE_FOLDS: TRUE
LOGGER_DIR: 'log'

IDS_FILES:
    TRAIN_FILE: folds/
    TEST_FILE: folds/test_id.csv

CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints/best
  TOPK: 4

WORKERS: 10
BATCH_SIZE: 10
EPOCHES: 35

FOLD:
  NUMBER: 5
  USEFOLDS: [0,1,2,3,4]

OPTIMIZER:
  CLASS: Adam
  ARGS:
    lr: 0.000075
    weight_decay: 0.00001
    
SCHEDULER:
 CLASS: CosineAnnealingLR
 ARGS: 
   T_max: 8
   eta_min: 0.0000001       
