PIPELINE_NAME: efficientnet-b3
TRAIN_PATH: 'cloudsimg/train_images'
TEST_PATH: 'cloudsimg/test_images'
PREPARE_FOLDS: True
LOGGER_DIR: 'log'

IDS_FILES:
    TRAIN_FILE: folds/
    TEST_FILE: folds/test_id.csv

CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints/best
  TOPK: 8

WORKERS: 8
BATCH_SIZE: 8
EPOCHES: 30

FOLD:
  NUMBER: 8
  USEFOLDS: [0,1,2,3,4,5,6,7]

OPTIMIZER:
  CLASS: Adam
  ARGS:
    lr: 0.00001
    weight_decay: 0.000005
    
SCHEDULER:
 CLASS: CosineAnnealingLR
 ARGS: 
   T_max: 8
   eta_min: 0.0000001       
