
NUM_WORKERS: 10
BATCH_SIZE: 2

CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints/best
  PIPELINE_PATH: configs/efficientnet-b3
  PIPELINE_NAME: efficientnet-b3

DICT_FOLDER: 'dict_efficientnet-b3'
SUBMIT_BEST: TRUE
USEFOLDS: [0]
SELECTED_CHECKPOINTS:
  fold0: [0,1,86,89]
RESULT: result_top3_folds.pkl
