
NUM_WORKERS: 10
BATCH_SIZE: 2

CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints/best
  PIPELINE_PATH: configs/efficientnet-b3
  PIPELINE_NAME: efficientnet-b3

DICT_FOLDER: 'dict_efficientnet-b3'
SUBMIT_BEST: FALSE
USEFOLDS: [0,1,2,3,4,5,6,7]
SELECTED_CHECKPOINTS:
  fold0: [6,7,8]
  fold1: [22,28,29]
  fold2: [26,28,29]
  fold3: [27,28,29]
  fold4: [27,28,29]
  fold5: [27,28,29]
  fold6: [27,28,29]
  fold7: [27,28,29]
RESULT: result_top3_folds.pkl
