
NUM_WORKERS: 10
BATCH_SIZE: 2

CHECKPOINTS:
  FULL_FOLDER: checkpoints
  BEST_FOLDER: checkpoints/best
  PIPELINE_PATH: configs/resnet34
  PIPELINE_NAME: resnet34

DICT_FOLDER: 'dict_resnet34'
SUBMIT_BEST: False
USEFOLDS: [0,1,2]
SELECTED_CHECKPOINTS:
  fold0: [0,3,4,6]
  fold1: [0,2,3,5]
  fold2: [0,2,3,8]
RESULT: result_top4_resnet_folds.pkl
